name: Docker Workflow

on:
  - push

jobs: 
  docker: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Docker Build Variables
      run: |
        echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}"
        echo "CONTAINER_REGISTRY=docker.io"
        echo "IMAGE_NAME=jeremiah-aidoo-github-actions"
        echo "Tag will be: $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest"

    - name: Docker Build
      env:
        CONTAINER_REGISTRY: docker.io
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}  # 'humble15'
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  # Your Docker Hub password or token
        IMAGE_NAME: jeremiah-aidoo-github-actions
      run: |
        # Print the values of the variables for debugging
        echo "Building Docker image with tag: $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest"
        
        # Build the Docker image with the correct tag
        docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest .

    - name: Docker Login
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}  # 'humble15'
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  # Your Docker Hub password or token
      run: echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin

    - name: Docker Publish 
      env:
        CONTAINER_REGISTRY: docker.io
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}  # 'humble15'
        IMAGE_NAME: jeremiah-aidoo-github-actions
      run: |
        # Print the tag before pushing
        echo "Pushing Docker image with tag: $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest"
        
        # Push the Docker image to Docker Hub
        docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Docker Run
      env:
        CONTAINER_REGISTRY: docker.io
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}  # 'humble15'
        IMAGE_NAME: jeremiah-aidoo-github-actions
      run: |
        # Print the tag before running
        echo "Running Docker container with tag: $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest"
        
        # Run the container with the correct tag
        docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
