name: Debug Docker Username

on:
  push:
    branches:
      - main

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if DOCKER_USERNAME is set
        run: |
          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
            echo "DOCKER_USERNAME is not set or is empty."
            exit 1
          else
            echo "DOCKER_USERNAME is set."
          fi

      - name: Display Docker Username (masked)
        run: echo "Docker username is: ${{ secrets.DOCKER_USERNAME }}"
