name: Docker Workflow

on:
  - push

jobs: 
  docker: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Docker Build
      env:
        CONTAINER_REGISTRY: docker.io
        DOCKER_USERNAME: humble15
        DOCKER_PASSWORD: Humblehak@1997
        IMAGE_NAME: jeremiah-aidoo-github-actions
      run: |
        docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest .

    - name: Docker Login
      env:
        DOCKER_USERNAME: humble15
        DOCKER_PASSWORD: Humblehak@1997
      run: echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin

    - name: Docker Publish 
      env:
        CONTAINER_REGISTRY: docker.io
        DOCKER_USERNAME: humble15
        IMAGE_NAME: jeremiah-aidoo-github-actions
      run: docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Docker Run
      env:
        CONTAINER_REGISTRY: docker.io
        DOCKER_USERNAME: humble15
        IMAGE_NAME: jeremiah-aidoo-github-actions
      run: |
        docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
